---

- name: Setup Jupyter Notebook
  hosts: jupyter_vm
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install pip
      apt:
        name: python3-pip
        state: present
    - name: Install Jupyter Notebook
      pip:
        name: notebook
        executable: pip3